### ISSUE TITLE
Change add/edit command format to the MS-OS style

### ISSUE THREAD

**Issue by xpdavid** [CS2103AUG2016-W09-C4/main#63]
- Add `add t/ TITLE [d/ DESCRIPTION] [s/ START] [e/ END] [c/ CATEGORY] ...`
- Edit `edit INDEX [t/ TITLE] [d/ DESCRIPTION] [s/ START] [e/ END] [c/ CATEGORY] ...`

**Comment by haiilong** [comment]
Resolve in branch:

https://github.com/CS2103AUG2016-W09-C4/main/tree/switch_to_MS-OS_style

@xpdavid HOWEVER: 2 PROBLEMS:
If I type:

add t/ haha d/ hehe

The title will be "haha d" because you separate the regex for each part. Been trying to find a work around but seriously cannot find any. If you do not have any suggestion maybe we use .t and .d or something since it is in front. If not please suggest/help me haha.

If this is resolve, all the logic test cases will be resolved, except GUI test.

**Comment by xpdavid** [comment]
@haiilong can use `/t` or `/d`, you can bring this to group chat

**Comment by haiilong** [comment]
Resolve in branch 

https://github.com/CS2103AUG2016-W09-C4/main/commits/switch_to_MS-OS_style.

I have made sure both GUI and non-GUI test cases pass

**Comment by xpdavid** [comment]
Solved in #68
